### PR TITLE
Cluster API: Bump to v1.15.2.

### PR DESCRIPTION
**Pull request by Gacko**
Changelog: https://github.com/giantswarm/cluster-api-app/blob/main/CHANGELOG.md
Comparison: https://github.com/giantswarm/cluster-api-app/compare/v1.14.0...v1.15.2

Towards https://github.com/giantswarm/giantswarm/issues/30063.

### CODE REVIEW

**Comment by glitchcrab** [comment]
we already have [this](https://github.com/giantswarm/cloud-director-app-collection/pull/71) but we're holding off merging until all MCs are on 1.25

**Comment by Gacko** [comment]
You won't be able to upgrade to v1.25.x without that. Versions older than v1.15.2 are not PSS compliant.

**Comment by glitchcrab** [comment]
yup, that's why we're running the upgraded MCs on Xavier's branch of this repo. once all of them are upgraded we'll merge the PR and revert them to main.

**Comment by Gacko** [comment]
Ah, ok. Then I'll close this PR and reference yours as solution for possible PSS issues on Cloud Director. Thanks!

**Pull request closed without merging**
